version: "3.3"

services:
  cherino:
    image: aloxaf/cherino:0.4.0
    container_name: cherino
    restart: unless-stopped
    volumes:
      - ./config.toml:/app/config.toml
    logging:
      options:
        max-size: "128m"