version: "3.3"

services:
  cherino:
    build: .
    restart: unless-stopped
    volumes:
      - ./config.toml:/app/config.toml
      - ./db.sqlite:/app/db.sqlite
      - ./db.sqlite-shm:/app/db.sqlite-shm
      - ./db.sqlite-wal:/app/db.sqlite-wal
