[tool.pdm]

[project]
name = "cherino"
version = "0.1.0"
description = "telegram group manager for exloli"
authors = [
    {name = "Aloxaf", email = "Aloxafx@gmail.com"},
]
dependencies = [
    "aiogram==3.0.0b7",
    "pydantic>=1.10.5",
    "tomlkit>=0.11.6",
    "peewee>=3.15.4",
    "apscheduler>=3.10.0",
    "cachetools>=4.2.4",
    "asyncache>=0.1.1",
    "loguru>=0.6.0",
    "aiogram-dialog==2.0.0b16",
]
requires-python = ">=3.10"
license = {text = "MIT"}

[project.scripts]
cherino = "cherino.main:main"
